<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The requested page does not exist.' => '',
    'Hash' => '哈希值',
    'Password' => '密码',
    'Password Repeat'=>'重复密码',
    'Admin Id' => '管理员id',
    'Admin Name' => '管理员名',
    'Admin Status'=>'管理员状态',
    'Ok'=>'成功',
    'Fail'=>'失败',
    'createTime' => '创建时间',
    'Header Img' => '头像',
    'Real Name' => '姓名',
    'Sex' => '性别',
    'Phone' => '手机号',
    'Update Time' => '更新时间',
    'Email' => '邮箱',
    'Data center number value error, value range is'=>'数据中心编号取值错误，取值范围为',
    'Wrong value of machine number, value range is'=>'机器编号取值错误，取值范围为',
    'The current time cannot be less than the last time!'=>'当前时间不能小于最后一次时间！',
    'Illegal request!'=>'非法请求！',
    'Request parameter cannot be empty!'=>'请求参数不能为空！',
    'Page'=>'第几页',
    'Limit'=>'每页数量',
    'The two passwords are inconsistent'=>'两次输入密码不一致！',
    'Repeat Password'=>'重复密码',
    'Email already exists'=>'邮箱已存在！',
    'Mobile number already exists'=>'手机号已存在！',
    'Users are not allowed to log in, please contact the administrator'=>'用户禁止登录，请联系管理员',
    'Wrong user name or password.'=>'用户名或密码错误',
    'Man'=>'男',
    'Woman'=>'女',
    'On'=>'开启',
    'Off'=>'禁止',
    'Salt Code'=>'随机id',
    'Verification Code'=>'验证码',
    'Verification code acquisition failed'=>'验证码获取失败',
    'Verification code error'=>'验证码错误',
    'Authority ID'=>'权限id',
    'Parent ID'=>'父级id',
    'Authority Code'=>'权限编码',
    'Authority Name'=>'权限名称',
    'Authority Show'=>'权限展示',
    'Authority Status'=>'权限状态',
    'Admin ID'=>'管理员id',
    'Role ID'=>'角色id',
    'Role Name'=>'角色名称',
    'Role Status'=>'角色状态',
    'Create Time'=>'创建时间',
    'Update at least one data'=>'至少更新一个数据',
    'Request ID cannot be empty'=>'请求id不能为空',
    'Hide'=>'隐藏',
    'Display'=>'显示',
    'Permission ID'=>'权限id',
];
